### ISSUE TITLE
Convert dates to the correct timezone

### ISSUE THREAD

**Issue by Nicd** [code-stats/code-stats#35]
Dates are now displayed based on UTC. But that's not correct for many users that are far from UTC. Could use something like moment.js to correct the dates?

**Comment by amandeepmittal** [comment]
Yes, momentjs will be a good module to use. You can take a look at [momentjs/timezone](https://momentjs.com/timezone/).

**Comment by Nicd** [comment]
This is actually partly fixed since we are now storing the local time and offset with all pulses. So we can use that and it does not need to be converted in most cases.
